from sys import argv, stderr
from flask import Flask, make_response, url_for, request
from flask import render_template
import random

app = Flask(__name__, template_folder='.')
info = \
 [{'Caption': 'For 37 years, Simeon Stylites lived his entire life confined to a small platform atop a pillar in Aleppo. This was not by imposition: Simeon decided to pursue a particular kind of asceticism, refusing to dismount even for food, as he relied entirely on the generosity of others for nourishment . His devotion was unwavering, as he breathed his final breath atop that same platform, now on a pillar more than 15 meters high, found dead while still hunched over in prayer.',
  'File Name': 'SaintSimeonStylites',
  'Question': 'Is it the mind that confines the body, and not the body that confines the mind?',
  'Source': 'The Column of Saint Simeon; photo taken in 2000',
  'Year': 459},
 {'Caption': 'Skeletons excavated from the monastic site of St. Stephen’s, dating back to Byzantine Jerusalem, often exhibit eburnation of the knee, a skeletal-degenerative disorder whereby the cartilage around the knee wears away, revealing subchondral bone. Historians speculate that these malformations were caused by constant and repetitive genuflection on the hard stone floors of the monastery during prayer and other religious rites. Prayer is the consummate attentional act; the will is focused so completely that devotional practice can supersede all other corporeal desires and instincts of self-preservation.',
  'File Name': 'EburnatedKnee',
  'Question': 'Is attention the force that shapes our actions?',
  'Source': 'Susan Guise Sheridan, “Pious Pain: Repetitive Motion Disorders from Excessive Genuflection at a Byzantine Jerusalem Monastery”, 2020; skeletal remains circa fifth to seventh centuries AD',
  'Year': 500},
 {'Caption': 'The Mykonos vase is one of the earliest-known objects to contain a depiction of the Trojan Horse from Homer’s Iliad. Greek soldiers famously hid themselves inside a wooden horse gifted to the city of Troy; enthrallment is what led their enemies to accept the gift within their walls, only for their expressions to become those of shock and dread as they were slaughtered. This archetype has been mnemonically echoed throughout history, manifesting itself in sources as varied as the mortal calculus of grand strategy and computer virus design.',
  'File Name': 'MykonosVase',
  'Question': 'How dangerous is the capacity to misdirect attention?',
  'Source': 'Unknown, “The Mykonos Vase”, 670 BCE; Mykonos Archaeological Museum',
  'Year': 670},
 {'Caption': 'The paradigm of an attention economy mandates a subject perennially and agentially attending in the world but, here, Augustine’s search for transcendent insight harkens back to a world where, instead of constant attentional movement, there is the possibility attentional withholding – a mental abeyance in a swamp of stimuli. Surrounded by open books calling him to write, he instead inscribes upon the pages within.',
  'File Name': 'Agustine',
  'Question': 'James Williams tells us attention is smothering our attentional spotlight – but what if we don’t produce any light in and of ourselves?',
  'Source': 'Vittore Carpaccio, Saint Augustine in His Study, 1507. Scuola di San Giorgio degli Schiavoni. © 2013. Photo: Scala, Florence',
  'Year': 1507},
 {'Caption': 'There is a lot in the setting of this painting that one could look at. With few exceptions, however, the eyes of all of the shepherds are fixed on Jesus Christ. This is a significant moment religiously, but other factors like the novelty of life and the fact that others are also paying attention, might inform to the group’s collective gaze.',
  'File Name': 'adoration_of_shepherds',
  'Question': 'What factors compel a group to collectively attend to something?',
  'Source': 'Aspertini, Amico. “Adoration of the Shepherds,” 1515; Galleria degli Uffizi, Florence, Italy.',
  'Year': 1515},
 {'Caption': "A page peers, with somber curiosity, into a pool of water surrounded by darkness. His reflection absorbs his attention and, like the chiaroscuro style of this painting, creates a stark contrast between that which is and isn't seen. The realism of Caravaggio didn't end with his extensive study of the physical human form given that his tenebrist style reflected the nature of human perception and attention as narrowly focused on few key aspects of the subject.",
  'File Name': 'narcissus',
  'Question': 'Which is more "accurate", the depiction of a scene as captured by a content-agnostic camera or a perceptually informed illustration which emphasizes the attentionally relevant aspects of the scene?',
  'Source': 'Michelangelo Caravaggio, "Narcissus", c. 1597-9; Galleria Nazionale d\'Arte Antica.',
  'Year': 1599},
 {'Caption': 'Marvelously embellished Quranic manuscripts such as the one above epitomized the intimate interrelationship between written word, knowledge, and the sacred in premodern cultures. Often surrounded by sophisticated geometric tessellations, the Word was merely distillation of the meaning permeating the physical universe. Learning was to attune one’s attention with the reverberations of the world.',
  'File Name': 'Quran',
  'Question': 'Has the disenchantment of modern pedagogy banalized our attention to information?',
  'Source': '"17th Century Persian Illuminated Quranic Manuscript." Digital image. Perkins School of Theology. Accessed April 28, 2021.',
  'Year': 1600},
 {'Caption': 'The classical model of the human subject has, as its core metaphor, the camera obscura. Some time between 1790 and 1860, the classical model came apart as refinements in the scientific method uncovered the complexity of perception. The deconstruction of the subject into constituent parts such as “attention” and “will” restabilized personhood while discarding the antiquated notions of the eternal soul.',
  'File Name': 'camera_obscura',
  'Question': 'How can we prevent advances in neuroscience and computational understandings of the brain from dehumanizing us?',
  'Source': 'Athanasius Kircher, Illustration of a "portable" camera obscura, 1646. Ars Magna Lucis Et Umbra',
  'Year': 1646},
 {'Caption': 'Islamic artforms are formed at the nexus of mathematics and theophany. Here, the concentric rims of design form attentional gradations – akin to the Buddhist meditative stages of realization – representing the stages a spiritual aspirant must struggle through each stage contracting in the number of forms as one moves inward to the center. In emphatic apophatic conclusion, the center becomes blackness of nothingness, the culmination of one’s negative attending – extinguishment.',
  'File Name': 'Taj',
  'Question': 'Does modernity leave derelict our ability to attend to things beyond our physical sensorium?',
  'Source': '"Taj Mahal Mosaic." Digital image. Mozaico. Accessed April 28, 2021.',
  'Year': 1650},
 {'Caption': 'Different characters in the painting are focused on different tasks: some on protecting themselves with shields, some on attacking with swords, some on attacking with their bodies.  The intertwining of bodies and weapons creates an almost indecipherable jumble in the center of this painting. But this confusing collision prolonged my gaze as I tried to distinguish the boundaries between humans and animals.',
  'File Name': 'battle_of_anghiari',
  'Question': 'In what circumstances can lack of understanding compel deeper attention?',
  'Source': 'Edenlinck, Gerard. “The Battle of Anghiari,” approx. 1673-1684; UCLA, Grunwald Center for the Graphic Arts.',
  'Year': 1673},
 {'Caption': 'The Kaaba is the center of the Muslim world as the direction of daily prayer and yearly pilgrimages for millions of people every year. The goal of the pilgrimage is not to enter or simply spectate the cuboid in the center of the square, rather the mandate is that Muslims circumambulate the Kaaba counterclockwise seven times. The speed of the circumambulation is to be faster on the outer ring and slower when closer to the Kaaba to create harmonic motion and unite with God.',
  'File Name': 'kaaba',
  'Question': 'How does synchronous motion as a religious goal unite populations differently from the more static and contemplative forms of religious attention?',
  'Source': 'Adriaan Reland, "View of the Kaaba", 1718; Peace Palace Library.',
  'Year': 1718},
 {'Caption': 'The refracting telescope acts as an object of attention for the people that surround it. In addition, however, the telescope is a means through which to pay attention. Looking through the telescope narrows the range of objects you can attend to and the lens you look through helps to create the image that appears.',
  'File Name': 'refracting_telescope',
  'Question': 'Does the intensity of attention change when the area you can see is narrowed?',
  'Source': 'Bianchini, Francesco. "1728 Refracting Telescope," 1728; California Room, San Jose Public Library. ',
  'Year': 1728},
 {'Caption': 'Sensationalized media have a long history in the United States, beginning with this engraving by Paul Revere of the Boston Massacre, which resulted in only four deaths. Paul Revere played an important role in the inception of revolutionary messaging as an artist and activist. It can sometimes be justified to capture attention for the wrong reasons, if towards a righteous goal.',
  'File Name': 'boston_massacre',
  'Question': 'Who will sound the alarm on the attentional crisis we face and is it possible to effectively do so without engaging in the very manipulate practices we seek to oppose?',
  'Source': 'Paul Revere, "The bloody massacre perpetrated in King Street Boston on March 5th 1770 by a party of the 29th Regt", March 5, 1770; Library of Congress',
  'Year': 1770},
 {'Caption': 'This early draft of the Great Seal of the United States features the eye of providence at the top of the design: a symbol which would go on to feature on every one dollar bill and on the seal of the DARPA Information Awareness Office. This all-seeing eye has been the subject of many conspiracies regarding the structure of the US government, given its similarity to "The Eye of God" in the Christian tradition and the evocation of an omniscient totalizing power at the top of the metaphysical hierarchy. The US has created both the PATRIOT Act to invade privacy and the Freedom of Information Act to reveal its excesses.',
  'File Name': 'eye_of_providence',
  'Question': 'What true conspiracies to control and monitor our attention exist in the US government and how can they coexist with corrective forces to ensure citizens are "free" from overreaches of government attention?',
  'Source': 'Pierre Eugene du Simitiere, "Original proposed design for the Great Seal of the United States", 1776; Library of Congress.',
  'Year': 1776},
 {'Caption': 'Totalizing surveillance without any practical escape characterizes the payment of the modern attentional transaction. Technologies both capture our attention as well as our behavioral patterns in its expenditure to best tailor to our most monetizable desires. We are the prisoners and piles of black box algorithms are already in the watchtower.',
  'File Name': 'panopticon',
  'Question': 'How can we recenter ourselves and liberate others from commodified hypervisibility?',
  'Source': 'Willey Reveley, "Plan of Jeremy Bentham\'s panopticon prison", 1791; The works of Jeremy Bentham vol. IV, 172-3.',
  'Year': 1791},
 {'Caption': 'Audiences were so enthralled by Paganini’s performances that they claimed he sold his soul to the devil and upon his death the Catholic Church denied him a burial for thirty six years. His technical prowess on the violin was so great that he modified famous concerti to better show off his talents. His eyes seem disembodied as he derealizes through musical self-expression and brings the audience along.',
  'File Name': 'paganini',
  'Question': 'How does deeply attentive performance engender temporary ego death or other transcendent experiences for the artist and the observers?',
  'Source': 'Richard James Lane, "Paganini", 1831. National Portrait Gallery, London.',
  'Year': 1831},
 {'Caption': 'In 1833, The New York Sun ‘shone for all’ at the cost of 1 cent. Grabbing the morning news, finally getting in touch with the happenings of the day, this was a newspaper for the common man. Feeling the newspaper in your hand, the common object which you held was identical to your neighbors.',
  'File Name': 'TheSunNewspaper',
  'Question': 'Are mediums born of expression or by means of exploitation?',
  'Source': 'National Museum of American History, Behring Center, January 4, 2013, https://americanhistory.si.edu/blog/2013/01/the-pony-press-and-the-patent-model-collection.html ',
  'Year': 1833},
 {'Caption': 'A realistic painting of a real place is the product of sustained attention. Artistic liberties might be taken, but outcome ultimately is a reflection of what the artistic paid attention to. The areas of light and dark water and the pink and gray of the sky could not be captured without the artist’s attention to those features.',
  'File Name': 'montevideo',
  'Question': 'What might be lost when we try to convert our observations into an artistic representation?',
  'Source': 'Raebel, Hermann. “Montevideo, Uruguay. S.A.,” 1866; UCLA Library Special Collections.',
  'Year': 1866},
 {'Caption': 'On February 21, 1804, the first ever steam-powered railway journey took place in South Wales. For the first time in human history, people were linked together with an unprecedented immediacy and efficiency. Humans, for the first time ever, found themselves accelerated faster than the world around them, watching after-images pass them, never within reach; the world could now be enjoyed transiently as a sedentary, accelerating experience… until the train crashes.',
  'File Name': 'TrainWreck',
  'Question': 'What will happen when your train crashes?',
  'Source': 'De Forest Douglas Diver Railroad Photographs, “O&W Wreck Loco. 140.”, circa 1870 - 1948; Cornell University Library',
  'Year': 1870},
 {'Caption': 'In Russian religious history, the holy fool is a recurring role of the itinerant ascetic, whose suffering parallels that of Christ before them. They often met bleak and untimely deaths, choosing to brave the savage cold, possessionless, until meeting their ends at the heavy hands of mobs or starvation. Asceticism has roots in many other world religions; it is the direction of attention away from all matters of the physical world and towards a stuporous communion with God.',
  'File Name': 'HolyFool',
  'Question': 'Is the human experience solely the product of selective attentional focus?',
  'Source': 'Pavel Svedomsky, “A God’s Fool”, late 19th century; Regional Art Museum Kirovograd',
  'Year': 1870},
 {'Caption': 'This panorama captures a wider range of view as a result of sewing three separate images of a location together. This allows a viewer of the panorama to attend to the scene in a way that would more closely match the way they’d attend to the view in person, where their peripheral vision would give them greater range than a camera can. But in expanding the range of view, a panorama might discourage a viewer from attending to the small details in order to examine the larger image.',
  'File Name': 'panorama',
  'Question': 'Are there advantages to paying attention to the larger scene represented in an image instead of the details of an image?',
  'Source': 'Oscanyan, Christopher. “Photo-panoramic view of Constantinople,” 1876; Library of Congress Prints and Photographs Division, Washington D.C.',
  'Year': 1876},
 {'Caption': 'Paris in the 1870’s was the origin of a revolution in Western art and imagination. Along came the Impressionists, who imagined the world around them not as a frozen, calculated snapshot of a single moment - like many of their predecessors had - but as a vibrant, moving after-image, imbued with the emotions and atmospheric impressions that would become reified as brush strokes on canvas. The artist’s attention was dislodged from the rut that it had become trapped in; it was free to imagine the experience of the human condition, not just its setting.',
  'File Name': 'TheCafe-Concert',
  'Question': 'How much of the world is experienced and attended to through impressions?',
  'Source': 'Edouard Manet, “The Cafe-Concert”, 1879; The Walters Art Museum, Baltimore',
  'Year': 1879},
 {'Caption': 'Each image capturing a different movement that makes up the kangaroo jump, the series captures the process as a whole. When captured as a series of images, the artist can see how each body part moves in a way that would not be visible in real-time observation. The still image capture in this situation allows a researcher to pause time in a sense in order to closely observe the phenomenon of a kangaroo jumping.',
  'File Name': 'kangaroo_jumping',
  'Question': 'What are the limits to our real-time attention?',
  'Source': 'Muybridge, Eadweard. “Kangaroo Jumping,” approx. 1884-1886; University of Pennsylvania, Philadelphia, PA.',
  'Year': 1884},
 {'Caption': 'In the late 1860’s, the streets and edifices of Paris bore witness to a new kind of advertisement: artistic advertisement posters - larger and more vibrant than ever before - that seemed to pull in any who passed by. Yet, it was only a matter of time before the posters became clutter, covering nearly every available surface in the city and obfuscating the beauty that they were originally conceptualized to productively enhance. An advertising tool whose aesthetic distinctiveness was key to its attention-catching capabilities expanded to fill the space provided until its powers asymptotically reduced to null, and not for the last time.',
  'File Name': 'FrenchAdvertisementPrint',
  'Question': 'What is to happen as our environment is slowly plastered over with a layer of attention-capturing technology?',
  'Source': 'H. Gray (Henri Boulanger), Untitled, 1898; advertising poster for Phebus bicycles',
  'Year': 1898},
 {'Caption': 'The front cover of a pamphlet about bananas, this picture serves as an advertisement for bananas at a time that bananas weren’t widely eaten. The historical context and recipes that follow familiarize the reader with what was a fruit that they may not have understood at the time. The choice by the United Fruit Company to make this advertisement seems to be reflective of a belief that understanding is integral to attention and engagement with a product.',
  'File Name': 'banana',
  'Question': 'Do we need understanding for attention?',
  'Source': 'Hill, Janet McKenzie. “A Short History of the Banana and a Few Recipes for its Use,” approx. 1904; UC San Diego Special Collections & Archives.',
  'Year': 1904},
 {'Caption': 'Public efforts to encourage citizens to act for the greater epidemiological good have looked very similar dating back to the Spanish influenza. It seems much more difficult to unite against and pay attention to a microscopic enemy than to political or even virtual enemies (in the form of video games or social media). "Civic patriotism" appears to be less important than more experientially immediate tribalism.',
  'File Name': 'mask',
  'Question': 'How can public health be improved by leveraging our attentional bias towards a tangible common enemy rather than pleas for selflessness?',
  'Source': 'Karl Friedrich Meyer, January 12, 1919, Section One, Page 23, Image 23, The Sunday Oregonian. University of Oregon Library.',
  'Year': 1919},
 {'Caption': 'Standardization and efficiency, the two gifts of the typewriter to state practices of record keeping, represented a fundamental shift in human practices of writing. Severing the hand, mechanical mediation made the word distanced and impersonal, catalyzing the banalization of knowledge into information. With the word no longer contiguous with the introspective subject but, now, simply produced by another object, attention falls out of the writer into the written.',
  'File Name': 'Typewriter',
  'Question': 'Do we attend better when we write than typing?',
  'Source': '"Post Office Order Machine." Digital image. Pinterest. Accessed April 28, 2021.',
  'Year': 1920},
 {'Caption': "Martín Chambi grew up in the rural Andes mountains where houses were arranged around a central communal patio. This photograph has been the center of my dining room wall ever since I can remember. The game they are playing is called sapo and consists of throwing bronze coins at a board hoping to land one in a bronze frog's mouth for maximum points, but the most fun part is gathering the coins back up again like the small child is doing.",
  'File Name': 'sapo',
  'Question': 'How can architecture shape the attention we pay one another, and improve the games we choose to play?',
  'Source': 'Martín Chambi, "Chicha and Sapo", c. 1925; Museum of Modern Art.',
  'Year': 1925},
 {'Caption': 'The tumblers are focused on their performance because their safety depends on it. The audience seem engaged, but upon further notice, we see a guard above the crowd. The scene takes place at a prison, where the audience could be coerced into paying attention by nature of being forced to be there.',
  'File Name': 'tumbling_competition',
  'Question': 'When attendance is forced, can we tell whether attention is voluntary or coerced?',
  'Source': 'Stanley, Leo. “Tumbling Competition, San Quentin Little Olympics Field Meet,” 1930; Marin County Free Library.',
  'Year': 1930},
 {'Caption': 'M. C. Escher beholds a reflective sphere in the middle of his study to see a fish-eyed distortion of the scene with the ego at the center. The only thing outside of the sphere is the disembodied left hand which could belong to anyone and leaves open the possibility that the hand belongs instead to the viewer, who is observing a self-contained spherical universe. Since lithography mirrors the original image when creating a print, the original model hand was Escher’s right hand, which he drew with his dominant left hand.',
  'File Name': 'escher',
  'Question': 'How universal would the property of reflection be if we paid sufficient attention to anything?',
  'Source': 'M. C. Escher, "Hand with Reflecting Sphere", January 1935; Escher in the Palace.',
  'Year': 1935},
 {'Caption': 'The year is 1935, and the daily newspaper is posted in your neighborhood. Your neighbors, peers, and workers crowding the stand. The headline is shocking.',
  'File Name': 'DerSturmer',
  'Question': 'Does the proliferation of information bring attentive bodies together or push them apart?',
  'Source': 'Facing HIstory and Ourselves, 16 Hurd Rd., Brookline, MA 02445. Accessed via https://www.facinghistory.org/resource-library/image/nazi-propaganda-newspaper. ',
  'Year': 1935},
 {'Caption': 'On one level, the photograph demands the attention of the photographer to focus the image, recruit subjects, and find good light. But on another level, the image was a product of the photographer’s attention to the societal conditions at the time – specifically, the poverty and struggle of the Great Depression. There is also attention involved in the consumption of this image by viewers, who find this image captivating not only because of the weight of the historical moment, but also because of their empathy towards the emotional struggle subtly expressed by the mother captured in this image.',
  'File Name': 'migrant_mother',
  'Question': 'Is all photography a practice of attention or is documentary photography more demanding of',
  'Source': 'Lange, Dorothea. “Migrant Mother,” 1936; National Museum of American History, Washington D.C.',
  'Year': 1936},
 {'Caption': 'It’s early Christmas morning, and you run to the living room to see what Santa has brought you. Unwrapping the gifts, you come across the Viewmaster, wondering what it is. Your mother, having one herself as a child, instructs you how to use it; you don’t play with any other toy all day.',
  'File Name': 'Viewmaster',
  'Question': 'What is the role of intergenerationality in consuming and how does it affect our means of attending to one another?',
  'Source': 'Accessed on Amazon, via <https://www.amazon.com/View-Master-2036-Boxed-Set/dp/B00F3WDGA6>. ',
  'Year': 1939},
 {'Caption': 'Spending time in a foreign country, doing fissured work, the screen is a haven for the soldier. Whether instructional or narrative, the whole camp collects around the screen, established by rafters or hanging from branches. The film captures all aspects of the war, both here and back home.',
  'File Name': 'OutdoorTheaterWW2',
  'Question': 'Is attention a tool of sympathy or community?',
  'Source': '"How the U.S. Army Served its Movie-Mad GIs during World War II", Tanya Goldman, The Unwritten Record, US National Archives. https://unwritten-record.blogs.archives.gov/2020/01/09/how-the-u-s-army-served-its-movie-mad-gis-during-world-war-ii/.  ',
  'Year': 1940},
 {'Caption': 'In December of 1941, the Japanese air force staged a surprise attack on the American naval base at Pearl Harbor, annihilating the US Pacific Fleet - the injured party declared war the very next day. Every newspaper in the country broadcasted the shocking news to the public; an entire nation, in unison, was deployed into battle. The same informational arteries that had been riling fighting spirits for the past 2 years were primed and ready to focus the national attention- they had, in part, created that very national attention.',
  'File Name': 'PearlHarborHeadline',
  'Question': 'Are we all synchronized along myriad matrices?',
  'Source': 'Front page of the Washington C.H.Record-Herald, Sunday, December 7, 1941',
  'Year': 1941},
 {'Caption': 'The US Navy’s MK 37 Gun Fire Control System was a finely-tuned informational network; an MK 1 computer is operated in conjunction with an MK 37 director, in conjunction with radar technicians and 7 other organic communicative links. An entire team of soldiers is enmeshed into a computerized network - like human gears - as the function, unwavering focus, and repetitive consistency expected from human operators is no different than that expected from their electronic compatriots. In the critical moment of battle, the living and sentient are brought in as surrogate parts for a system of the unliving and unaware.',
  'File Name': 'Mark37',
  'Question': 'Are you being used as a human gear?',
  'Source': 'US Navy, Mark 37 Director',
  'Year': 1941},
 {'Caption': 'A diary is a chronicle of attendance. Nothing that you do not attend to can make its way in there. Even the act of writing is a form of attention: grasping the pen, attending to the paper, and tracking the letters that come out of each movement.',
  'File Name': 'diary',
  'Question': 'If a diary tracks what we attend to, are there other ways to track the day-to-day things that we don’t attend to?',
  'Source': 'Kikuchi, Charles. “Charles Kikuchi original diary: Volume 15,” 1942; UCLA Special Collections Library.',
  'Year': 1942},
 {'Caption': 'Martín Chambi took one of the first selfies with Machu Picchu, using a carefully placed tripod and long wire to activate the camera discreetly while posing in front of one of the seven wonders of the world. He then still had to descend the mountain and develop the film before he could see how the picture had turned out. During this entire process of image creation, he undoubtedly must have reflected on the legacy of the Inca Empire and his relationship to it.',
  'File Name': 'mountain_selfie',
  'Question': 'How does diminished latency in the cycle of self-examination shift attentional focus from that which has been or might be to that which is?',
  'Source': 'Martín Chambi, "Autoretrato", 1943; COYA Art Collection.',
  'Year': 1943},
 {'Caption': 'The hand-cranked record player fills the room as more people file into the tent. The V-discs issued by Army Special Services are only about six-minutes long. Mood Indigo by Dinah Shore, in its quiet, soft-spoken tone, fills the tent.',
  'File Name': 'SoldiersNormandyVinyl',
  'Question': 'Is attention an act of escape or immersion?',
  'Source': 'Macklem, Mary. “War, Vinyl and Print: Music for the Troops during World War II.” The National Endowment for the Humanities, 10 Aug. 2015, https://www.neh.gov/divisions/research/featured-project/war-vinyl-and-print-music-the-troops-during-world-war-ii. ',
  'Year': 1944},
 {'Caption': 'At 5:29 AM on July 16, 1945, J. Robert Oppenheimer watched as 5,300 pounds worth of plutonium implosion fission incinerated the surrounding area at temperatures 10-thousand times hotter than the surface of the Sun and a 7.5-mile high cloud of death towered before him. He was famously reminded of the Bhagavad-Gita: “Now I am become Death, the destroyer of worlds.” A 2000-year old vision is realized as humanity is explosively, blindingly confronted with its own capacity for apocalyptic devastation.',
  'File Name': 'TrinityTest',
  'Question': 'How can you pay attention to anything else?',
  'Source': 'United States Department of Energy, “Trinity and Beyond: the Atomic Bomb Movie”, 16 July 1945',
  'Year': 1945},
 {'Caption': 'Glenn Gould was a Canadian classical pianist, renowned for his superlative technique and the richness of his interpretive insights. His performances were known for their near-theatrical atmosphere, as Gould eschewed the stoic conventions of traditional piano performance; he would move his body erratically as he played, often humming along to the notes. He was totally absorbed into his instrument and his craft, as he surrendered body and mind to the music, losing control of his movements while still obsessively focused on perfecting his environment for performance. It could be said that his life and mind became music.',
  'File Name': 'GlennGould',
  'Question': 'Do attentional scenes condition the human experience, or does the human experience condition its attentional scenes?',
  'Source': '1950; Glenn Gould’s debut recording of the Goldberg Variations, Columbia Records, New York City',
  'Year': 1950},
 {'Caption': 'Billy Graham is considered perhaps the most influential evangelist to ever march across the plains of Protestant American Christendom in the twentieth century. Attracting unprecedented masses to his fiery preaching through new media such as radio and television, Graham appears at the heels of the fusion of the sublimity of religious experience into the very same media used for the commodification of attention, whose product was televangelism, a superfetation of the Trinity with another man. One could say that the 20th century American culture of celebrity idolization seems to have found an ironic resonance.',
  'File Name': 'Graham',
  'Question': 'Does mass attention to externalized performance pose grave hazard to protracted inward exercise, the fundamental thrust of any religious enterprise?',
  'Source': '"Billy Graham." Digital image. Life and Legacy of Billy Graham. Accessed April 28, 2021.',
  'Year': 1950},
 {'Caption': 'I, Ayn Rand, "will never live for the sake of another man". Individual rights are right and laissez faire capitalism is the most fair through its objective rationality. She had an inner circle of close individualist friends including Alan Greenspan, who went on to influence the development of the dot-com bubble and subprime mortgage crisis.',
  'File Name': 'ayn_rand',
  'Question': 'When does restricting attention to analysis of the individual lead to collectively undesirable Nash equilibria of exclusively selfish behavior?',
  'Source': 'Ayn Rand in front of Grand Central in midtown Manhattan in 1957. New York Times Co. (Getty Images)',
  'Year': 1957},
 {'Caption': 'The cloth mother lives in the deepest recesses of the uncanny valley. Lifeless yet warm, friendly yet neglectful, it seems to fulfill some psychological need of the infant monkey which takes precedence over subsistence in its hierarchy of needs. The monkey seems confused and saddened by the inanimate choices of mother available, whose impact manifests later in life as extremely antisocial behavior.',
  'File Name': 'behaviorism',
  'Question': 'What role does attentive nurture (as opposed to strictly efficient resource distribution) play in effective parenting?',
  'Source': 'Harlow, H. F. (1958). The nature of love. American Psychologist, 13(12), 673-685. https://dx.doi.org/10.1037/h0047884',
  'Year': 1958},
 {'Caption': 'Approaching a rally, the sound can overtake you. Chants, scattered conversations, arguments, megaphones and microphones. But, when the time comes, the entire crowd quiets, and only a select few are heard.',
  'File Name': 'JudyCollinsVietnamRally',
  'Question': 'What power lies behind collective attention?',
  'Source': '“Judy Collins Singing at Anti-Vietnam War Rally. Kezar Stadium, San Francisco, CA. 1967.” National Museum of American History, https://americanhistory.si.edu/collections/search/object/nmah_892487. Accessed 27 Apr. 2021.',
  'Year': 1967},
 {'Caption': "The daily newspaper in hand, with the family gathered around the television. The newspaper gives way to the new footage from the war, as they broadcast images of violence. It's all the same in the papers. ",
  'File Name': 'VietnamWarPaperTV',
  'Question': 'What does the popularity of certain mediums over others assert about attention?',
  'Source': 'Leffler, Warren K, photographer. A man and a woman watching a film footage of the Vietnam war on a television in their living room / WKL. Photograph. Retrieved from the Library of Congress, <www.loc.gov/item/2011661230/>.',
  'Year': 1968},
 {'Caption': 'Walking into the theater is nothing new, but this time, a pair of flimsy eyeglasses is given out at the door. Marveled as the new format for the film, the images, seemingly only an offset, blurred image, takes on a 3-dimensional form. The stereoscopic process has begun, and the movie leaps into reality.',
  'File Name': 'societyofthespectacle',
  'Question': 'Does attention desire interactivity?',
  'Source': 'Debord, Guy. Society of the Spectacle. Detroit: Black & Red, 1983. Accessed via <https://libcom.org/library/society-of-the-spectacle-debord>. ',
  'Year': 1970},
 {'Caption': 'On the 19th of November, 1971, American artist Chris Burden stood still in an art gallery as a friend shot him through the arm. The injury was part of a performance art piece, titled Shoot, intended as a jarring critique of the routinization and formalization of violence during the Vietnam War-era. As a pioneer of the Body Art movement, Burden used his corporeality as a medium for articulation and artistic expression, piercing through more traditional modes of expression and into a gripping space of visceral humanity and mortality.',
  'File Name': 'Shoot',
  'Question': 'Can the brutality of attention sound the alarm bell?',
  'Source': 'Chris Burden, “Shoot”, 1971; private gallery show',
  'Year': 1971},
 {'Caption': 'Henry Joseph Darger Jr. was an American outsider artist and novelist who lived and worked as a custodian in Chicago. Over the course of six decades, he completed 15,145-page, single-spaced, work, titled The Story of the Vivian Girls, in What is Known as the Realms of the Unreal, of the Glandeco-Angelinian War Storm Caused by the Child Slave Rebellion. Adorned with hundreds of detailed watercolor illustrations, his magnum opus was an immense feat, requiring a lifetime of obsessive attention and dedication, pushing writerly work to its limits.',
  'File Name': 'HenryDarger',
  'Question': 'Where did Darger really exist - in the realms of the “real” or in the Realms of the Unreal?',
  'Source': 'David Berglund, Portrait of Henry Darger, 1971',
  'Year': 1971},
 {'Caption': 'Long lines stretch out the door of the memorial building for Chairman Mao of China. This seems to be an illustration of the loyalty of Mao’s constituents. But it could also symbolically represent not only their loyalty to him, but their alignment with the values and beliefs of Mao.',
  'File Name': 'memorial_dedication',
  'Question': 'Is loyalty to a person or cause a form of attention?',
  'Source': 'Cui, Kaixi & Gao, Quan. “Common wish of the people, in congratulation on the establishment of the Charirman Mao Memorial Hall,” 1977; UCLA Special Collections and Archives.',
  'Year': 1977},
 {'Caption': "Rest Energy is a 1980 performance art piece by Marina Abramovic and Ulay where, for four minutes, an arrow was drawn and pointed at Abramovic’s heart, kept at bay solely by the bodyweight and volition of her partner. The two leaned back against the force of the bow, listening to each other's heartbeats through microphones on their chests, hearing the rhythms accelerate as their entire lives converged on one focal point. Both artists were drawn into a mortal balance of attention: Abramovic’s entire existence relied on the tension of a bow- on the tension of two lovers.",
  'File Name': 'RestEnergy',
  'Question': 'In a less dramatic sense, are they not us all? Is attention not what we balance all our lives on?',
  'Source': 'Marina Abramovic and Ulay, Rest Energy, 1980; Netherlands Media Art Institute',
  'Year': 1980},
 {'Caption': 'One "tank man" is powerless to stop "progress". This photo was taken the day after protests were violently suppressed in Tiananmen square and the tanks are fleeing the scene. In the wake of the massive protests demanding justice, he merely waits on the powerful.',
  'File Name': 'tank_man',
  'Question': 'How does visibility of contemplative resistance change its efficacy by pausing attention to create a reflective moment?',
  'Source': 'Jeff Widener, "Tank Man", June 5, 1989. Associated Press',
  'Year': 1989},
 {'Caption': 'From the moment he rose to power in 1949, Chairman Mao Zedong made himself the nexus of the inchoate People’s Republic of China. The public was inundated with aggrandizing propaganda, a little red book, and even four different titles for their new leader. The chairman’s power crystallized from the concentrated attention and exaltation of hundreds of millions, all directed towards one man.',
  'File Name': 'MaoBadges',
  'Question': 'Who are you letting stand upon your attention?',
  'Source': 'Gary Tamin, “Chairman Mao”, 2006',
  'Year': 2006},
 {'Caption': 'The ticket cost is high, even for a normal matinee. But, the folks at the museum say that this experience is worth it. Laying back in the cushioned seat, putting on the somewhat familiar 3D glasses, you notice an aroma as the 4D movie kicks in.',
  'File Name': '4DTheaterBoston',
  'Question': 'How many dimensions exist in the attentional space?',
  'Source': 'Museum of Science 4D Theater, Boston, MA; Torrey Architecture, <https://www.torreyarchitecture.com/projects/museum-of-science-4d-theater>.',
  'Year': 2014},
 {'Caption': 'This image, which captures a moment in which a celebrity is attending to the fan that is attending to the celebrity, can be understood as a subversion of the assumption that celebrities don’t notice when their fans are attending to them. The celebrity is demonstrating that he notices the “subtle” ways that people attend to him, and that there is reciprocity in the attention. The stated goal of his Instagram documentation of fans taking photos is to participate in a “camera duel” – that is, to repeatedly attempt to be so adept at noticing the recognition behaviors of a fan that he can take a picture of the fan before the fan can take a picture of him.',
  'File Name': 'camera_duel',
  'Question': 'How does the status of a person factor into our assumptions about their attention?',
  'Source': 'Sprouse, Cole. Untitled, 2014; https://www.instagram.com/camera_duels/',
  'Year': 2014},
 {'Caption': 'The autoplay feature facilitates the continuation of attention by eliminating the action required to maintain it. With this feature, inaction is continuation. Only active action via pausing or turning off the TV can stop the process.',
  'File Name': 'autoplay',
  'Question': 'What is the significance of technology that carries your attention forward without your active consent?',
  'Source': 'Tanous, Jim. Photo of Netflix Autoplay. 2015. https://www.techjunkie.com/how-to-stop-netflix-from-automatically-playing-the-next-episode/.',
  'Year': 2015},
 {'Caption': 'I bought a PC to play Counter-Strike: Global Offensive, a modern shooter which hosts competitions on the global stage. Now, I watch Twitch streamers who bet on skins. The excitement, the thrill of winning or losing… I could use a skin.',
  'File Name': 'CSGoSkinGambling',
  'Question': 'Can attention manifest value? ',
  'Source': 'Campbell, Colin, "The True Cost of Counter-Strike Skin Gambling", <https://www.polygon.com/features/2016/7/18/12203534/counter-strike-cs-go-skin-gambling> ',
  'Year': 2016},
 {'Caption': 'Although there’s no cigarette smoke, no groups of drunk young people, and no difference between night and day, this casino still has all the usual trappings. Blackjack, Texas Hold ‘Em and all iterations of the slot machine. You never need to go home; you’re already there.',
  'File Name': 'VRCasino',
  'Question': 'Does virtual reality immerse or disembody a subject?',
  'Source': 'Beckett, Samantha, “An Inside Look At Virtual Reality & The Casino Industry”, Casino.org, Oct. 17th, 2016.',
  'Year': 2016},
 {'Caption': 'The home button is an active recentering. With one click you can find your way out of the cycle of usage and return to a familiar space. From there you can once again make the active choice of where to go next: to stop usage or continue in a new direction.',
  'File Name': 'home_button',
  'Question': 'Does a recentering tool help to break the addictive features built into apps in practice? ',
  'Source': 'Benjamin, Jeff. iPhone Home Button. 2016. https://9to5mac.com/2016/10/03/opinion-new-iphone-7-home-button/.',
  'Year': 2016},
 {'Caption': 'Signs of the Times (2017) was an art installation project by Scott Kelly and Ben Polkinghorne, placing “recommendations” at the sites of numerous travel destinations and significant locales. The signs were intended to become intrusion made manifest, drawing attention to the growing infringement of digital algorithms upon physical reality. As the world has come to internalize the relational-computational logic of machines, the things we attend to are increasingly mediated by a layer of recommendations.',
  'File Name': 'SignOfTheTimes',
  'Question': 'In a world saturated with recommendations, how can we know that our will is truly our own?',
  'Source': 'Scott Kelly and Ben Polkinghorne, “Signs of the Times”, 2017; art installation',
  'Year': 2017},
 {'Caption': 'Quran reciters tour the globe, extending an ancient acoustic oral tradition into the sensorium of the modern. A mob of microphones amplify their voice - at times ironically masking it in noise – disseminating sound beyond even the auditorium. Upon finishing a verse, crowd jumps in amazement, sometimes performing feats of affection more jaw dropping than the recitation itself.',
  'File Name': 'QuranMic',
  'Question': 'What makes this type of sacred performativity different from a profane one?',
  'Source': '"Mahmoud Shahat Anwar." Digital image. YouTube. Accessed April 28, 2021.',
  'Year': 2017},
 {'Caption': 'Jeff, Mark, Sundar, and Jack. How much of your day and life do they control? At least you can see nuclear warheads coming. These platforms suffuse themselves in our lives without allowing us to notice their spread while preventing us from attending to hardly anything else. Thanks to their ubiquity and manufactured insularity, meaningless lives are medicated and bad ideas are legitimized.',
  'File Name': 'mass_distraction',
  'Question': 'How do we defuse the potential violence fostered by these systems?',
  'Source': 'Gasaway, Rich. “Weapons of Mass Distraction.” Situational Awareness Matters!™, 15 Nov. 2019, www.samatters.com/weapons-of-mass-distraction/. ',
  'Year': 2019},
 {'Caption': "At the VA Hospital, there’s a new form of therapy available. Rather than taking medication or laying back on a recliner, therapy involves a trip into virtual reality. Kenneth Stewart, the man in the photograph, described the experience, stating; “It's so realistic. I wish I could go there.”",
  'File Name': 'VRTherapyVeteran',
  'Question': 'Where can the virtual mend the real?',
  'Source': 'Najarro, Ileana, “Virtual Reality Helps Ease Trauma for Patients at Tampa Veterans Hospital”, St. Petersberg, Florida, Tampa Bay Times, November 30th, 2019.',
  'Year': 2019},
 {'Caption': 'In this image, a dog is being trained with the help of a clicker and treats, a process that requires attentiveness on the part of the dog to perform the desired behavior and on the part of the human to acknowledge the desired behavior through using a clicker and offering a treat. This common training strategy of clicking the clicker and rewarding the dog with a treat interestingly diverges from the finding of B.F. Skinner (as described by Wu) that the behaviors constantly rewarded are actually more prone to extinction than behaviors that are inconsistently rewarded. Would training a dog to perform a certain behavior work better if the dog were inconsistently rewarded?',
  'File Name': 'dog_training',
  'Question': 'How does the nature of attention change with inconsistent reward?',
  'Source': 'Puppy Leaks. “How to Get Started With Clicker Training Your Dog.” https://www.puppyleaks.com/clicker-training-dog-basics/, January 29, 2019.',
  'Year': 2019},
 {'Caption': 'Driving into the movie theatre, the attendant takes your ticket, and motions to your parking spot. You find it, park, and await the concessions worker to order some popcorn and candy for your movie. You look across the aisle, viewing families, couples, or just lone moviegoers, all in their own spot.',
  'File Name': 'DriveInTheatre',
  'Question': 'Does the attentively demanding move towards separation?',
  'Source': 'Stars and Stripes Drive-In Theatre, Stars & Stripes Drive-In Facebook, Texas Film Commission, 2021. <https://gov.texas.gov/film/trail/stars-stripes-drive-in-theatre>.',
  'Year': 2020},
 {'Caption': 'The circle, once a symbol of the infinity of the Divine in premodernity, has now mutated in the modern imagination into the form of a refresh loop. Suctions of attention, refresh loops operate on the logic codified by Skinner in which it is merely the potential of reward that conditions our longing to refresh. Not different from how gamblers experience the Zone, affect becomes algorithm.',
  'File Name': 'Cycles',
  'Question': 'How can modernity announce progress yet only produce circles?',
  'Source': '"Refresh Icon." Digital image. Online Web Fonts.',
  'Year': 2020},
 {'Caption': 'And they’re off! You’ve studied the different races, researched different NFT stud farms, and awaited this race. On your computer screen, your horse outpaces the others, and your heart rises.',
  'File Name': 'ZedHorseRacing',
  'Question': 'How does the non-fungible online interact with the non-fungible offline?',
  'Source': 'Feldman, Jacob. “People Are Breeding Digital Horses, And Spending Real Money”, Sportico Media, April 20th, 2021.',
  'Year': 2021},
 {'Caption': 'Microsoft’s 21.9 Billion dollar defense contract shows that augmented and virtual reality are here to stay. With thermal optics and night vision, along with communication and targeting features, these headsets are set to change warfare. Soldiers won’t be seen, or heard, but detected.',
  'File Name': 'MicrosoftHUD',
  'Question': 'How will the virtual battlefield overlay the real?',
  'Source': 'Thompson, Elaine, Associated Press, “Microsoft will make augmented reality headsets for the Army in a $21.9 billion deal.” By Kellen Browning, New York, New York Times, March 31, 2021.',
  'Year': 2021}]
@app.route('/', methods=['GET'])
@app.route('/home', methods=['GET'])
@app.route('/index', methods=['GET'])
def home():
    html = render_template('home.html')
    response = make_response(html)
    return response

@app.route('/scene', methods=['GET'])
def scene():
    image = random.choice(info)
    
    order = request.args.get('order')
    index = request.args.get('index')
    if (order and index):
        image = info[int(index)]
    html = render_template('scene.html',
            image=image, order=order, index=index)
    response = make_response(html)
    return response